set_property PACKAGE_PIN R8 [get_ports adrv1_refclk_p]
set_property PACKAGE_PIN L8 [get_ports adrv2_refclk_p]
set_property PACKAGE_PIN E10 [get_ports {adrv1_sysref_p[0]}]
set_property PACKAGE_PIN F15 [get_ports {adrv2_sysref_p[0]}]
set_property PACKAGE_PIN R4 [get_ports {rxp_adrv1[0]}]
set_property PACKAGE_PIN P2 [get_ports {rxp_adrv1[1]}]
set_property PACKAGE_PIN M2 [get_ports {rxp_adrv1[2]}]
set_property PACKAGE_PIN L4 [get_ports {rxp_adrv1[3]}]
set_property PACKAGE_PIN K2 [get_ports {rxp_adrv2[0]}]
set_property PACKAGE_PIN H2 [get_ports {rxp_adrv2[1]}]
set_property PACKAGE_PIN G4 [get_ports {rxp_adrv2[2]}]
set_property PACKAGE_PIN F2 [get_ports {rxp_adrv2[3]}]

set_property PACKAGE_PIN V2 [get_ports {adrv1_sync0_p[0]}]
set_property PACKAGE_PIN W2 [get_ports {adrv1_sync1_p[0]}]
set_property PACKAGE_PIN T1 [get_ports {adrv2_sync0_p[0]}]
set_property PACKAGE_PIN U2 [get_ports {adrv2_sync1_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adrv1_sync0_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adrv1_sync0_n[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adrv1_sync1_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adrv1_sysref_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adrv2_sync0_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adrv2_sync1_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adrv2_sysref_p[0]}]

set_property PACKAGE_PIN A12 [get_ports {rst_lmk_p[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rst_lmk_p[0]}]

